// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptemialurdeeoctlorae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0ZW1pYWx1cmRlZW9jdGxvcmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODI2MzksImV4cCI6MjA2NTU1ODYzOX0.u7-Ul7NtYcBhzb1SDU_tJTjH6RPmdEhQCPpsK1LyI50";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);